content:
  - name: 1eraño
    label: "1er Año"
    type: collection
    path: "clases/1eraño/arteypatrimonio/clase"
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: markdown }