# Decap CMS Configuration File

# The backend option specifies how to access the content for your site
backend:
  name: git-gateway
  branch: master # The branch to update (optional; defaults to master)