local_backend: true

backend:
  name: git-gateway
  branch: main # The branch to update (optional; defaults to master)

media_folder: ""

collections:
  - name: "arteypatrimonio1eraño"
    label: "Arte y Patrimonio - 1er Año"
    folder: "src/clases/1eraño/arteypatrimonio/clase"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "matematica1eraño"
    label: "Matematicas - 1er Año"
    folder: "src/clases/1eraño/matematicas/clase"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "arteypatrimonio2doaño"
    label: "Arte y Patrimonio - 2do Año"
    folder: "src/clases/2doaño/arteypatrimonio/clase"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}



